version: '3'

services:
  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./config/trombi.sql:/docker-entrypoint-initdb.d/trombi.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trombiDb

  php-app:
    build:
      context: ./server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://username:password@db:5432/trombiDb?serverVersion=15&charset=utf8"

  react-app:
    build:
      context: ./clientapp
    ports:
      - "3000:3000"
    volumes:
      - ./clientapp:/clientapp
    depends_on:
      - db

volumes:
  pg_data:
