controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

peoples:
    path: /api/v1/peoples
    controller: App\Controller\PeoplesController::index
    methods: [GET]

#
#   name: string
#   firstname: string
#
peoples_show:
    path: /api/v1/people
    controller: App\Controller\PeoplesController::show
    methods: [GET]

#
#   name: string
#   firstname: string
#   job: string
#
peoples_update_job:
    path: /api/v1/people/update/job
    controller: App\Controller\PeoplesController::updateJob
    methods: [PATCH]

#
#   name: string
#   firstname: string
#   equip: string
#
peoples_update_equip:
    path: /api/v1/people/update/equip
    controller: App\Controller\PeoplesController::updateEquip
    methods: [PATCH]

#
#   name: string
#   firstname: string
#   agency: string
#
peoples_update_agency:
    path: /api/v1/people/update/agency
    controller: App\Controller\PeoplesController::updateAgency
    methods: [PATCH]

users:
    path: /api/v1/users
    controller: App\Controller\UsersController::index
    methods: [GET]

users_show:
    path: /api/v1/user/{username}
    controller: App\Controller\UsersController::show
    methods: [GET]

#
#   username: string
#   password: string
#
users_create:
    path: /api/v1/user/create
    controller: App\Controller\UsersController::create
    methods: [POST]

#
#   username: string
#   password: string
#
users_login:
    path: /api/v1/user/login
    controller: App\Controller\UsersController::login
    methods: [GET]
