controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

peoples:
    path: /api/v1/peoples
    controller: App\Controller\PeoplesController::index
    methods: [GET]

peoples_show:
    path: /api/v1/peoples/{name}
    controller: App\Controller\PeoplesController::show
    methods: [GET]

users:
    path: /api/v1/users
    controller: App\Controller\UsersController::index
    methods: [GET]

users_show:
    path: /api/v1/users/{username}
    controller: App\Controller\UsersController::show
    methods: [GET]
