controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

peoples:
    path: /api/v1/peoples
    controller: App\Controller\PeoplesController::index
    methods: [GET]

peoples_show:
    path: /api/v1/people/{name}
    controller: App\Controller\PeoplesController::show
    methods: [GET]

users:
    path: /api/v1/users
    controller: App\Controller\UsersController::index
    methods: [GET]

users_show:
    path: /api/v1/user/{username}
    controller: App\Controller\UsersController::show
    methods: [GET]

users_create:
    path: /api/v1/user/create
    controller: App\Controller\UsersController::create
    methods: [POST]

users_login:
    path: /api/v1/user/login
    controller: App\Controller\UsersController::login
    methods: [GET]
