controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

customers:
    path: /api/v1/customers
    controller: App\Controller\CustomerController::index
    methods: [GET]
