controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

peoples:
    path: /api/v1/peoples
    controller: App\Controller\PeopleController::index
    methods: [GET]

peoples_show:
    path: /api/v1/peoples/{id}
    controller: App\Controller\PeopleController::show
    methods: [GET]